services:
  windrose:
    build:
      context: .
      args:
        WINE_FLAVOR: stable
    image: ${IMAGE_NAME:-localhost/windrose-ds:dev}
    pull_policy: never
    environment:
      UPDATE_ON_START: ${UPDATE_ON_START:-false}
    volumes:
      - ./scripts:/opt/windrose/scripts:ro
